spring.application.name=SpringCloudConfigServer

server.port=8888
spring.cloud.config.server.git.uri=ssh://localhost/EsercizioSpringBoot/RepositorySpringCloudConfigServer
#C:\EsercizioSpringBoot\RepositorySpringCloudConfigServer
#Verifica se si verificano problemi all’avvio del repository
spring.cloud.config.server.git.clone-on-start=true
#Disabilita la security del Management endpoint per rendere l’esercizio più semplice
management.security.enabled=false
